[tool.isort]
profile = "black"
src_paths = ["python/src", "python/test"]
line_length = 120

[tool.black]
src-paths = ["python/src", "python/test"]
line-length = 120

[tool.pylint]
max-line-length = 120
max-attributes=10
disable = """
	fixme,
	missing-class-docstring,
    missing-function-docstring,
    missing-module-docstring,
    too-few-public-methods,
"""