from typing import ClassVar

from exercise_log.constants import ROOT_ONTOLOGY_DIR
from exercise_log.utils import StrEnum

# Dynamically create these enums using a shared definition
enum_base_dir = f"{ROOT_ONTOLOGY_DIR}/enum/strength/anatomy"
Muscle = StrEnum.create_from_json(f"{enum_base_dir}/muscle.json", __name__)
MuscleGroup = StrEnum.create_from_json(f"{enum_base_dir}/muscle_group.json", __name__)

# TODO(eric): ideally a simple lookup like this can be handled as part of the StrEnum generation
Muscle.get_muscle_group = lambda self: MUSCLE_GROUP_MAP[self]

MUSCLE_GROUP_MAP: ClassVar[dict[str, MuscleGroup]] = {
    Muscle.OBLIQUES: MuscleGroup.ABS,
    Muscle.PYRAMIDALIS: MuscleGroup.ABS,
    Muscle.RECTUS_ABDOMINUS: MuscleGroup.ABS,
    Muscle.TRANSVERSE_ABDOMINUS: MuscleGroup.ABS,
    Muscle.BICEPS_BRACHII_SHORT: MuscleGroup.BICEPS,
    Muscle.BICEPS_BRACHII_LONG: MuscleGroup.BICEPS,
    Muscle.BRACHIALIS: MuscleGroup.BICEPS,
    Muscle.POPLITEUS: MuscleGroup.CALVES,
    Muscle.TIBIALIS_ANTERIOR: MuscleGroup.CALVES,
    Muscle.TIBIALIS_POSTERIOR: MuscleGroup.CALVES,
    Muscle.GASTROCNEMIUS_LATERAL: MuscleGroup.CALVES,
    Muscle.GASTROCNEMIUS_MEDIAL: MuscleGroup.CALVES,
    Muscle.SOLEUS: MuscleGroup.CALVES,
    Muscle.FIBULARIS: MuscleGroup.CALVES,
    Muscle.FIBULARIS_TERTIUS: MuscleGroup.CALVES,
    Muscle.EXTENSOR_DIGITORUM_LONGUS: MuscleGroup.CALVES,
    Muscle.EXTENSOR_HALLUCIS_LONGUS: MuscleGroup.CALVES,
    Muscle.FLEXOR_DIGITORUM_LONGUS: MuscleGroup.CALVES,
    Muscle.FLEXOR_HALLUCIS_LONGUS: MuscleGroup.CALVES,
    Muscle.DELTOID_ANTERIOR: MuscleGroup.DELTS,
    Muscle.DELTOID_MEDIAL: MuscleGroup.DELTS,
    Muscle.DELTOID_POSTERIOR: MuscleGroup.DELTS,
    Muscle.FLEXOR_CARPI_ULNARIS: MuscleGroup.FOREARMS,
    Muscle.FLEXOR_CARPI_RADIALIS: MuscleGroup.FOREARMS,
    Muscle.PRONATOR_TERES: MuscleGroup.FOREARMS,
    Muscle.FLEXOR_DIGITORUM_SUPERFICIALIS: MuscleGroup.FOREARMS,
    Muscle.FLEXOR_POLLICIS_LONGUS: MuscleGroup.FOREARMS,
    Muscle.FLEXOR_DIGITORUM_PROFUNDUS: MuscleGroup.FOREARMS,
    Muscle.PRONATOR_QUADRATUS: MuscleGroup.FOREARMS,
    Muscle.EXTENSOR_CARPI_RADIALIS_BREVIS: MuscleGroup.FOREARMS,
    Muscle.EXTENSOR_DIGITORUM: MuscleGroup.FOREARMS,
    Muscle.EXTENSOR_CARPI_ULNARIS: MuscleGroup.FOREARMS,
    Muscle.EXTENSOR_CARPI_MINIMI: MuscleGroup.FOREARMS,
    Muscle.EXTENSOR_CARPI_RADIALIS_LONGUS: MuscleGroup.FOREARMS,
    Muscle.BRACHIORADIALIS: MuscleGroup.FOREARMS,
    Muscle.SUPINATOR: MuscleGroup.FOREARMS,
    Muscle.ABDUCTOR_POLLICIS: MuscleGroup.FOREARMS,
    Muscle.EXTENSOR_POLLICIS_LONGUS: MuscleGroup.FOREARMS,
    Muscle.EXTENSOR_INDICIS: MuscleGroup.FOREARMS,
    Muscle.GLUTEUS_MAXIMUS: MuscleGroup.GLUTES,
    Muscle.GLUTEUS_MEDIUS: MuscleGroup.GLUTES,
    Muscle.GLUTEUS_MINIMUS: MuscleGroup.GLUTES,
    Muscle.BICEP_FEMORIS_SHORT: MuscleGroup.HAMSTRINGS,
    Muscle.BICEP_FEMORIS_LONG: MuscleGroup.HAMSTRINGS,
    Muscle.SEMIMEMBRANOSUS: MuscleGroup.HAMSTRINGS,
    Muscle.SEMITENDINOSUS: MuscleGroup.HAMSTRINGS,
    Muscle.TENSOR_FASCIAE_LATAE: MuscleGroup.HIP_ABDUCTORS,
    Muscle.PIRIFORMUS: MuscleGroup.HIP_ABDUCTORS,
    Muscle.OBTURATOR: MuscleGroup.HIP_ABDUCTORS,
    Muscle.GEMELLUS: MuscleGroup.HIP_ABDUCTORS,
    Muscle.ADDUCTOR_LONGUS: MuscleGroup.HIP_ADDUCTORS,
    Muscle.ADDUCTOR_BREVIS: MuscleGroup.HIP_ADDUCTORS,
    Muscle.ADDUCTOR_MAGNUS: MuscleGroup.HIP_ADDUCTORS,
    Muscle.GRACILLIS: MuscleGroup.HIP_ADDUCTORS,
    Muscle.QUADRATUS_FEMORIS: MuscleGroup.HIP_ADDUCTORS,
    Muscle.ILIACUS: MuscleGroup.HIP_FLEXORS,
    Muscle.PSOAS: MuscleGroup.HIP_FLEXORS,
    Muscle.PECTINEUS: MuscleGroup.HIP_FLEXORS,
    Muscle.SARTORIUS: MuscleGroup.HIP_FLEXORS,
    Muscle.LATISSIMUS_DORSI: MuscleGroup.LATS,
    Muscle.PECTORALIS_MAJOR_CLAVICULAR: MuscleGroup.PECS,
    Muscle.PECTORALIS_MAJOR_STERNOCOSTAL: MuscleGroup.PECS,
    Muscle.PECTORALIS_MINOR: MuscleGroup.PECS,
    Muscle.SUBCLAVIUS: MuscleGroup.PECS,
    Muscle.RECTUS_FEMORIS: MuscleGroup.QUADS,
    Muscle.VASTUS_LATERALIS: MuscleGroup.QUADS,
    Muscle.VASTUS_MEDIALIS: MuscleGroup.QUADS,
    Muscle.VASTUS_INTERMEDIUS: MuscleGroup.QUADS,
    Muscle.TRAPEZIUS_UPPER: MuscleGroup.TRAPS,
    Muscle.TRAPEZIUS_MIDDLE: MuscleGroup.TRAPS,
    Muscle.TRAPEZIUS_LOWER: MuscleGroup.TRAPS,
    Muscle.TRICEPS_BRACHII_LONG: MuscleGroup.TRICEPS,
    Muscle.TRICEPS_BRACHII_LATERAL: MuscleGroup.TRICEPS,
    Muscle.TRICEPS_BRACHII_MEDIAL: MuscleGroup.TRICEPS,
    Muscle.RHOMBOID_MAJOR: MuscleGroup.RHOMBOIDS,
    Muscle.RHOMBOID_MINOR: MuscleGroup.RHOMBOIDS,
    Muscle.SUPRASPINOUS: MuscleGroup.ROTATOR_CUFF,
    Muscle.INFRASPINOUS: MuscleGroup.ROTATOR_CUFF,
    Muscle.TERES_MINOR: MuscleGroup.ROTATOR_CUFF,
    Muscle.SUBSCAPULARIS: MuscleGroup.ROTATOR_CUFF,
    Muscle.SERRATUS_ANTERIOR: MuscleGroup.SERRATUS,
    Muscle.SERRATUS_POSTERIOR_SUPERIOR: MuscleGroup.SERRATUS,
    Muscle.SERRATUS_POSTERIOR_INFERIOR: MuscleGroup.SERRATUS,
    Muscle.ILIOCOSTALIS_CERVICIS: MuscleGroup.SPINAL_ERECTORS,
    Muscle.ILIOCOSTALIS_THORACIS: MuscleGroup.SPINAL_ERECTORS,
    Muscle.ILIOCOSTALIS_LUMBORUM: MuscleGroup.SPINAL_ERECTORS,
}
